server:
  port: 8081
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestcjh@gmail.com
    password: xohvhfpztqxdzaqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3305/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.hyewon.routine_project.vo
custom:
  siteName: ROUTINE
  siteMainUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: ROUTINE
file:
  dir: C:\KHW\workspace\routine_project\group_profile